============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.4, pluggy-1.5.0
rootdir: /home/lucasalves/lucas/games-review
configfile: pytest.ini
plugins: cov-6.0.0
collected 0 items

WARNING: Failed to generate report: No data to report.


=============================== warnings summary ===============================
../../.cache/pypoetry/virtualenvs/games-review-ShunGJP9-py3.10/lib/python3.10/site-packages/_pytest/config/__init__.py:1441
  /home/lucasalves/.cache/pypoetry/virtualenvs/games-review-ShunGJP9-py3.10/lib/python3.10/site-packages/_pytest/config/__init__.py:1441: PytestConfigWarning: Unknown config option: DJANGO_SETTINGS_MODULE
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
------ generated xml file: /home/lucasalves/lucas/games-review/pytest.xml ------

---------- coverage: platform linux, python 3.10.12-final-0 ----------

============================== 1 warning in 0.02s ==============================
